### ISSUE TITLE
Transmutation Table Bug

### ISSUE THREAD

**Issue by RedBlueDevil** [Slowpoke101/Odyssey#2]
After getting about 10E emc into the transmutation table/tablet, I am no longer able to put items into the transmutation table/tablet. I can still put the items into the personal emc link but not the table/tablet.

**Comment by RedBlueDevil** [comment]
Also, there seems to be another bug. I linked my AE system to a compressed refined emc link with a storage bus. Now when I try to request things from the AE system and I click next, It just says "waiting for server". When I disconnected the compressed refined emc link from the AE system, everything went back to normal.

**Comment by DinnerBeef** [comment]
Please put issues here 
https://github.com/FTBTeam/FTB-Sky-Odyssey
When there make sure this is not a duplicet
